### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by chronicl** [naipofo/yomishi#1]
Hey 👋 
I would love to be able to use some parts from yomishi-core for my own little project.
If you are fine with external use of yomishi-core, could you please add a permissive license to this repo?

Great project btw!

**Comment by naipofo** [comment]
Hello, thanks for the interest.
Unfortunately, I'm not sure if i can license this project under a permissive license since some parts of it could be taken as re-written from [yomichan](https://github.com/FooSoft/yomichan) which is shared under a GPLv3 license. E.g. the search algorithm is practically the same and deflection data is just copied. So most likely i will share my project with the same license.
Are you ok with GPLv3 or maybe there is some proper way to license the part of the code you care about differently? Personally i don't mind other people re-using my code.

I've hoped to finish this project and give it a license long time ago but for many reasons I'm unable at the moment :/

**Comment by chronicl** [comment]
I see, the parts you mentioned are exactly what I would want to use. GPLv3 is not great, but it would be good enough, however my project is still in its infancy and there is no need to worry about licenses too much. For now I'm happy knowing that at least GPLv3 would be available if I ever need it, but you can leave it as is for now.

Thank you!
